import { Router, type IRouter } from "express";
import { eq } from "drizzle-orm";
import { db } from "@workspace/db";
import { casesTable, documentsTable } from "@workspace/db";
import { PDFDocument, PDFFont, StandardFonts, rgb, degrees } from "pdf-lib";

const router: IRouter = Router();

router.get("/cases/:id/forms/sc100", async (req, res): Promise<void> => {
  const raw = Array.isArray(req.params.id) ? req.params.id[0] : req.params.id;
  const id = parseInt(raw, 10);
  if (isNaN(id)) {
    res.status(400).json({ error: "Invalid case ID" });
    return;
  }

  const [c] = await db.select().from(casesTable).where(eq(casesTable.id, id));
  if (!c) {
    res.status(404).json({ error: "Case not found" });
    return;
  }

  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([612, 792]);
  const { width, height } = page.getSize();

  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const regularFont = await pdfDoc.embedFont(StandardFonts.Helvetica);

  const navy = rgb(0.05, 0.15, 0.35);
  const gold = rgb(0.85, 0.70, 0.10);
  const black = rgb(0, 0, 0);
  const gray = rgb(0.5, 0.5, 0.5);
  const lightGray = rgb(0.9, 0.9, 0.9);

  page.drawRectangle({ x: 0, y: height - 80, width, height: 80, color: navy });
  page.drawText("SC-100 PLAINTIFF'S CLAIM AND ORDER TO GO TO SMALL CLAIMS COURT", {
    x: 30, y: height - 35, size: 11, font: boldFont, color: rgb(1, 1, 1),
  });
  page.drawText("California Small Claims Court — Generated by Small Claims Genie", {
    x: 30, y: height - 55, size: 8, font: regularFont, color: rgb(0.8, 0.8, 0.8),
  });
  page.drawText(`Case: ${c.title}`, {
    x: 30, y: height - 70, size: 8, font: regularFont, color: gold,
  });

  let y = height - 105;

  const drawSection = (title: string): void => {
    page.drawRectangle({ x: 20, y: y - 2, width: width - 40, height: 20, color: lightGray });
    page.drawText(title, { x: 25, y: y + 2, size: 9, font: boldFont, color: navy });
    y -= 25;
  };

  const drawField = (label: string, value: string | null | undefined, wide = false): void => {
    const colWidth = wide ? width - 60 : (width - 70) / 2;
    page.drawText(`${label}:`, { x: 25, y, size: 8, font: boldFont, color: gray });
    page.drawText(value || "[Not provided]", { x: wide ? 130 : 100, y, size: 8, font: regularFont, color: value ? black : rgb(0.7, 0.7, 0.7) });
    page.drawLine({ start: { x: wide ? 130 : 100, y: y - 2 }, end: { x: wide ? width - 30 : 100 + colWidth, y: y - 2 }, thickness: 0.5, color: lightGray });
    y -= 18;
  };

  const drawTwoFields = (label1: string, val1: string | null | undefined, label2: string, val2: string | null | undefined): void => {
    const halfWidth = (width - 60) / 2;
    page.drawText(`${label1}:`, { x: 25, y, size: 8, font: boldFont, color: gray });
    page.drawText(val1 || "[Not provided]", { x: 100, y, size: 8, font: regularFont, color: val1 ? black : rgb(0.7, 0.7, 0.7) });
    page.drawLine({ start: { x: 100, y: y - 2 }, end: { x: 25 + halfWidth, y: y - 2 }, thickness: 0.5, color: lightGray });
    page.drawText(`${label2}:`, { x: width / 2 + 10, y, size: 8, font: boldFont, color: gray });
    page.drawText(val2 || "[Not provided]", { x: width / 2 + 70, y, size: 8, font: regularFont, color: val2 ? black : rgb(0.7, 0.7, 0.7) });
    page.drawLine({ start: { x: width / 2 + 70, y: y - 2 }, end: { x: width - 30, y: y - 2 }, thickness: 0.5, color: lightGray });
    y -= 18;
  };

  drawSection("PLAINTIFF (The person filing the claim)");
  drawTwoFields("Name", c.plaintiffName, "Phone", c.plaintiffPhone);
  drawField("Address", [c.plaintiffAddress, c.plaintiffCity, c.plaintiffState, c.plaintiffZip].filter(Boolean).join(", "), true);
  drawField("Email", c.plaintiffEmail, true);
  y -= 5;

  drawSection("DEFENDANT (The person or company you are suing)");
  drawTwoFields("Name", c.defendantName, "Phone", c.defendantPhone);
  drawField("Address", [c.defendantAddress, c.defendantCity, c.defendantState, c.defendantZip].filter(Boolean).join(", "), true);
  if (c.defendantIsBusinessOrEntity) {
    drawField("Agent for Service", c.defendantAgentName, true);
  }
  drawField("Is Business or Entity?", c.defendantIsBusinessOrEntity ? "Yes" : "No");
  y -= 5;

  drawSection("CLAIM DETAILS");
  drawTwoFields("Claim Type", c.claimType, "Claim Amount", c.claimAmount ? `$${c.claimAmount.toFixed(2)}` : null);
  drawTwoFields("Incident Date", c.incidentDate, "Filing County", c.countyId?.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase()) ?? null);
  y -= 5;

  page.drawText("Description of Claim:", { x: 25, y, size: 8, font: boldFont, color: gray });
  y -= 14;
  const descLines = wrapText(c.claimDescription || "[Not provided]", 80);
  for (const line of descLines.slice(0, 5)) {
    page.drawText(line, { x: 30, y, size: 8, font: regularFont, color: c.claimDescription ? black : rgb(0.7, 0.7, 0.7) });
    y -= 13;
  }
  y -= 5;

  drawSection("AMOUNT CALCULATION");
  const calcLines = wrapText(c.howAmountCalculated || "[Not provided]", 90);
  for (const line of calcLines.slice(0, 3)) {
    page.drawText(line, { x: 30, y, size: 8, font: regularFont, color: c.howAmountCalculated ? black : rgb(0.7, 0.7, 0.7) });
    y -= 13;
  }
  y -= 5;

  drawSection("PRIOR DEMAND");
  drawTwoFields("Demand Made?", c.priorDemandMade === true ? "Yes" : c.priorDemandMade === false ? "No" : null, "Venue Basis", c.venueBasis);
  if (c.priorDemandDescription) {
    drawField("Demand Description", c.priorDemandDescription, true);
  }
  y -= 5;

  drawSection("ADDITIONAL INFORMATION");
  drawTwoFields("Suing Public Entity?", c.isSuingPublicEntity ? "Yes" : "No", "Atty Fee Dispute?", c.isAttyFeeDispute ? "Yes" : "No");
  drawTwoFields("Filed 12+ Claims?", c.filedMoreThan12Claims ? "Yes" : "No", "Claim Over $2,500?", c.claimOver2500 ? "Yes" : "No");
  if (c.isSuingPublicEntity && c.publicEntityClaimFiledDate) {
    drawField("Public Entity Claim Filed", c.publicEntityClaimFiledDate);
  }

  y -= 15;
  page.drawRectangle({ x: 20, y: y - 40, width: width - 40, height: 45, color: rgb(0.98, 0.98, 0.88), borderColor: gold, borderWidth: 1 });
  page.drawText("IMPORTANT: This is a DRAFT generated by Small Claims Genie. Review all information carefully before filing.", {
    x: 30, y: y - 10, size: 7.5, font: boldFont, color: rgb(0.6, 0.5, 0),
  });
  page.drawText("This document is for preparation purposes only. You must file official SC-100 forms at your county courthouse.", {
    x: 30, y: y - 23, size: 7.5, font: regularFont, color: rgb(0.5, 0.5, 0),
  });
  page.drawText(`Small Claims Genie is not a law firm and this is not legal advice. Generated: ${new Date().toLocaleDateString()}`, {
    x: 30, y: y - 36, size: 7, font: regularFont, color: gray,
  });

  const pdfBytes = await pdfDoc.save();

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="SC100-Case-${id}-Draft.pdf"`);
  res.setHeader("Content-Length", pdfBytes.length);
  res.send(Buffer.from(pdfBytes));
});

router.get("/cases/:id/forms/sc100/preview", async (req, res): Promise<void> => {
  const raw = Array.isArray(req.params.id) ? req.params.id[0] : req.params.id;
  const id = parseInt(raw, 10);
  if (isNaN(id)) {
    res.status(400).json({ error: "Invalid case ID" });
    return;
  }

  const [c] = await db.select().from(casesTable).where(eq(casesTable.id, id));
  if (!c) {
    res.status(404).json({ error: "Case not found" });
    return;
  }

  res.json({
    plaintiffName: c.plaintiffName,
    plaintiffAddress: [c.plaintiffAddress, c.plaintiffCity, c.plaintiffState, c.plaintiffZip].filter(Boolean).join(", "),
    plaintiffPhone: c.plaintiffPhone,
    plaintiffEmail: c.plaintiffEmail,
    defendantName: c.defendantName,
    defendantAddress: [c.defendantAddress, c.defendantCity, c.defendantState, c.defendantZip].filter(Boolean).join(", "),
    defendantPhone: c.defendantPhone,
    defendantIsBusinessOrEntity: c.defendantIsBusinessOrEntity,
    defendantAgentName: c.defendantAgentName,
    claimAmount: c.claimAmount,
    claimType: c.claimType,
    claimDescription: c.claimDescription,
    incidentDate: c.incidentDate,
    howAmountCalculated: c.howAmountCalculated,
    priorDemandMade: c.priorDemandMade,
    priorDemandDescription: c.priorDemandDescription,
    venueBasis: c.venueBasis,
    venueReason: c.venueReason,
    countyId: c.countyId,
    isSuingPublicEntity: c.isSuingPublicEntity,
    publicEntityClaimFiledDate: c.publicEntityClaimFiledDate,
    isAttyFeeDispute: c.isAttyFeeDispute,
    filedMoreThan12Claims: c.filedMoreThan12Claims,
    claimOver2500: c.claimOver2500,
  });
});

function wrapText(text: string, maxChars: number): string[] {
  const words = text.split(" ");
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    if ((current + " " + word).trim().length <= maxChars) {
      current = current ? current + " " + word : word;
    } else {
      if (current) lines.push(current);
      current = word;
    }
  }
  if (current) lines.push(current);
  return lines;
}

export default router;
