// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/SC100CoordsMockup.tsx": () => import("../components/mockups/SC100CoordsMockup.tsx"),
  "./components/mockups/TextColorComparison.tsx": () => import("../components/mockups/TextColorComparison.tsx"),
  "./components/mockups/case-header/CaseHeader.tsx": () => import("../components/mockups/case-header/CaseHeader.tsx"),
  "./components/mockups/chat-expand/ExpandIcon.tsx": () => import("../components/mockups/chat-expand/ExpandIcon.tsx"),
  "./components/mockups/chat-expand/FullscreenOverlay.tsx": () => import("../components/mockups/chat-expand/FullscreenOverlay.tsx"),
  "./components/mockups/chat-expand/SlideUpSheet.tsx": () => import("../components/mockups/chat-expand/SlideUpSheet.tsx"),
  "./components/mockups/forms-wizard/FormsWizard.tsx": () => import("../components/mockups/forms-wizard/FormsWizard.tsx"),
  "./components/mockups/step-nav/VariantA.tsx": () => import("../components/mockups/step-nav/VariantA.tsx"),
  "./components/mockups/step-nav/VariantB.tsx": () => import("../components/mockups/step-nav/VariantB.tsx"),
  "./components/mockups/step-nav/VariantC.tsx": () => import("../components/mockups/step-nav/VariantC.tsx"),
  "./components/mockups/step-nav/VariantD.tsx": () => import("../components/mockups/step-nav/VariantD.tsx"),
  "./components/mockups/video-card/IntakeVideoCard.tsx": () => import("../components/mockups/video-card/IntakeVideoCard.tsx")
};
