import { pgTable, text, serial, timestamp, integer, real, boolean, jsonb } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const casesTable = pgTable("cases", {
  id: serial("id").primaryKey(),
  userId: text("user_id"),
  title: text("title").notNull(),
  status: text("status").notNull().default("draft"),
  countyId: text("county_id"),
  claimAmount: real("claim_amount"),
  claimType: text("claim_type"),
  plaintiffName: text("plaintiff_name"),
  plaintiffPhone: text("plaintiff_phone"),
  plaintiffAddress: text("plaintiff_address"),
  plaintiffCity: text("plaintiff_city"),
  plaintiffState: text("plaintiff_state").default("CA"),
  plaintiffZip: text("plaintiff_zip"),
  plaintiffEmail: text("plaintiff_email"),
  defendantName: text("defendant_name"),
  defendantPhone: text("defendant_phone"),
  defendantAddress: text("defendant_address"),
  defendantCity: text("defendant_city"),
  defendantState: text("defendant_state").default("CA"),
  defendantZip: text("defendant_zip"),
  defendantIsBusinessOrEntity: boolean("defendant_is_business_or_entity").default(false),
  defendantAgentName: text("defendant_agent_name"),
  claimDescription: text("claim_description"),
  incidentDate: text("incident_date"),
  howAmountCalculated: text("how_amount_calculated"),
  priorDemandMade: boolean("prior_demand_made"),
  priorDemandDescription: text("prior_demand_description"),
  venueReason: text("venue_reason"),
  venueBasis: text("venue_basis"),
  courthouseId: text("courthouse_id"),
  courthouseName: text("courthouse_name"),
  courthouseAddress: text("courthouse_address"),
  courthouseCity: text("courthouse_city"),
  courthouseZip: text("courthouse_zip"),
  courthousePhone: text("courthouse_phone"),
  courthouseWebsite: text("courthouse_website"),
  courthouseClerkEmail: text("courthouse_clerk_email"),
  filingFee: integer("filing_fee"),
  isSuingPublicEntity: boolean("is_suing_public_entity").default(false),
  publicEntityClaimFiledDate: text("public_entity_claim_filed_date"),
  isAttyFeeDispute: boolean("is_atty_fee_dispute").default(false),
  filedMoreThan12Claims: boolean("filed_more_than_12_claims").default(false),
  claimOver2500: boolean("claim_over_2500").default(false),
  intakeStep: integer("intake_step").default(1),
  intakeComplete: boolean("intake_complete").default(false),
  documentCount: integer("document_count").default(0),
  readinessScore: integer("readiness_score").default(0),
  demandLetterText: text("demand_letter_text"),
  demandLetterTone: text("demand_letter_tone"),
  settlementLetterText: text("settlement_letter_text"),
  settlementLetterTone: text("settlement_letter_tone"),
  settlementAgreementText: text("settlement_agreement_text"),
  evidenceChecklist: jsonb("evidence_checklist"),
  // ── Court hearing info (entered after filing, once court responds) ──────────
  caseNumber: text("case_number"),
  hearingDate: text("hearing_date"),
  hearingTime: text("hearing_time"),
  hearingJudge: text("hearing_judge"),
  hearingCourtroom: text("hearing_courtroom"),
  hearingNotes: text("hearing_notes"),
  // ── Email reminder tracking ──────────────────────────────────────────────────
  reminder30DaySent: boolean("reminder_30_day_sent").default(false),
  reminder14DaySent: boolean("reminder_14_day_sent").default(false),
  reminder7DaySent: boolean("reminder_7_day_sent").default(false),
  reminder3DaySent: boolean("reminder_3_day_sent").default(false),
  reminder1DaySent: boolean("reminder_1_day_sent").default(false),
  reminderNoHearingDateSent: boolean("reminder_no_hearing_date_sent").default(false),
  confirmationEmailSent: boolean("confirmation_email_sent").default(false),
  weeklyReminderLastSent: timestamp("weekly_reminder_last_sent", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const insertCaseSchema = createInsertSchema(casesTable).omit({ id: true, createdAt: true, updatedAt: true });
export type InsertCase = z.infer<typeof insertCaseSchema>;
export type Case = typeof casesTable.$inferSelect;
