/**
 * AZ Small Claims Complaint
 *
 * Programmatically generated with pdf-lib — no template PDF required.
 * Arizona Justice Court small claims forms do not use a single numbered
 * statewide AcroForm PDF, so this follows the same programmatic precedent
 * as VA DC-402 / NC AOC-CVM-200 / WA MISC 05.0100.
 *
 * Legal basis:
 *   A.R.S. § 22-501 through § 22-524 — Small Claims Division, Justice Court
 *   Claim limit: $5,000 (A.R.S. § 22-503) — individuals and businesses alike
 *   Attorneys prohibited unless all parties stipulate in writing (A.R.S. § 22-512)
 *   No appeal from a small claims judgment (A.R.S. § 22-519)
 */

import { PDFDocument, PDFPage, StandardFonts, rgb, PDFFont } from "pdf-lib";
import type { FormDefinition, FormBody, GenerateOptions } from "../registry";
import { FormRegistry } from "../registry";
import type { CaseData } from "../types";

const PW = 612;
const PH = 792;
const BLACK = rgb(0, 0, 0);
const GRAY = rgb(0.5, 0.5, 0.5);
const LIGHT = rgb(0.93, 0.93, 0.93);
const TEAL = rgb(0.05, 0.42, 0.37);

const ML = 54;
const MR = PW - 54;

function drawLine(page: PDFPage, x1: number, y1: number, x2: number, y2: number, thickness = 0.5, color = BLACK) {
  page.drawLine({ start: { x: x1, y: y1 }, end: { x: x2, y: y2 }, thickness, color });
}

function drawRect(page: PDFPage, x: number, y: number, w: number, h: number, fill = LIGHT) {
  page.drawRectangle({ x, y, width: w, height: h, color: fill, borderColor: BLACK, borderWidth: 0.5 });
}

function txt(page: PDFPage, font: PDFFont, text: string | null | undefined, x: number, y: number, size = 9, color = BLACK) {
  if (!text) return;
  page.drawText(String(text), { x, y, size, font, color });
}

function wrapText(page: PDFPage, font: PDFFont, text: string, x: number, y: number, maxWidth: number, size = 9, lineGap = 4): number {
  const words = text.replace(/\r/g, "").split(/\s+/).filter(Boolean);
  let line = "";
  let curY = y;
  for (const word of words) {
    const candidate = line ? line + " " + word : word;
    if (font.widthOfTextAtSize(candidate, size) > maxWidth && line) {
      txt(page, font, line, x, curY, size);
      curY -= size + lineGap;
      line = word;
    } else {
      line = candidate;
    }
  }
  if (line) { txt(page, font, line, x, curY, size); curY -= size + lineGap; }
  return curY;
}

function fmtAmount(amount: number | null | undefined): string {
  if (!amount) return "";
  return amount.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function fmtDate(iso?: string | null): string {
  if (!iso) return "";
  const [y, m, d] = iso.split("-");
  if (!y || !m || !d) return iso;
  return `${m}/${d}/${y}`;
}

function courthouseDisplay(countyId?: string | null): { court: string; county: string } {
  if (!countyId) return { court: "Justice Court", county: "" };
  const parts = countyId.replace(/^az-/, "").split("-");
  if (parts.length < 2) return { court: "Justice Court", county: parts[0] ?? "" };
  const county = parts[0].charAt(0).toUpperCase() + parts[0].slice(1);
  const precinct = parts.slice(1).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");
  return {
    court: `${county} County Justice Court — ${precinct} Precinct`,
    county,
  };
}

export async function buildAZComplaint(
  d: CaseData,
  _body: FormBody,
  opts?: GenerateOptions,
): Promise<Buffer> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  const page = doc.addPage([PW, PH]);
  const { court, county } = courthouseDisplay((d as any).countyId);

  let y = PH - 36;

  // ── Header ──────────────────────────────────────────────────────────────────
  const hdr1 = `${court}, State of Arizona`;
  const hdr2 = "SMALL CLAIMS COMPLAINT";

  const h1w = bold.widthOfTextAtSize(hdr1, 10);
  txt(page, bold, hdr1, (PW - h1w) / 2, y, 10);
  y -= 15;
  const h2w = bold.widthOfTextAtSize(hdr2, 12);
  txt(page, bold, hdr2, (PW - h2w) / 2, y, 12);
  y -= 10;
  const formNote = "A.R.S. § 22-501 et seq. — Claim limit: $5,000 — No attorneys (A.R.S. § 22-512) — No appeal (A.R.S. § 22-519) — Form generated by Small Claims Genie";
  const fnW = font.widthOfTextAtSize(formNote, 6.5);
  txt(page, font, formNote, (PW - fnW) / 2, y, 6.5, GRAY);
  y -= 12;

  txt(page, bold, "CASE NO.:", MR - 200, y + 24, 8);
  txt(page, font, d.caseNumber ?? "(assigned by court)", MR - 148, y + 24, 8, d.caseNumber ? BLACK : GRAY);

  drawLine(page, ML, y, MR, y, 1.2, TEAL);
  y -= 14;

  // ── Plaintiff / Defendant columns ────────────────────────────────────────────
  const COL_MID = ML + (MR - ML) / 2;
  drawRect(page, ML, y - 1, COL_MID - ML - 4, 14, LIGHT);
  drawRect(page, COL_MID, y - 1, MR - COL_MID, 14, LIGHT);
  txt(page, bold, "PLAINTIFF (You — the person filing)", ML + 4, y + 2, 8.5);
  txt(page, bold, "DEFENDANT (Person/Business You Are Suing)", COL_MID + 4, y + 2, 7.5);
  y -= 16;

  const PC = ML + 4;
  const DC = COL_MID + 4;
  const CW = COL_MID - ML - 12;

  const pName = (d as any).plaintiffDbaName
    ? `${d.plaintiffName ?? ""} d/b/a ${(d as any).plaintiffDbaName}`
    : (d.plaintiffName ?? "");

  txt(page, bold, "Name:", PC, y, 8);
  txt(page, font, pName, PC + 34, y, 8);
  txt(page, bold, "Name:", DC, y, 8);
  txt(page, font, d.defendantName ?? "", DC + 34, y, 8);
  y -= 12;

  txt(page, bold, "Address:", PC, y, 8);
  wrapText(page, font, d.plaintiffAddress ?? "", PC + 44, y, CW - 44, 8, 3);
  txt(page, bold, "Address:", DC, y, 8);
  wrapText(page, font, d.defendantAddress ?? "", DC + 44, y, CW - 44, 8, 3);
  y -= 12;

  txt(page, bold, "City/State/ZIP:", PC, y, 8);
  txt(page, font, [d.plaintiffCity, "AZ", d.plaintiffZip].filter(Boolean).join(", "), PC + 72, y, 8);
  txt(page, bold, "City/State/ZIP:", DC, y, 8);
  txt(page, font, [d.defendantCity, d.defendantState ?? "AZ", d.defendantZip].filter(Boolean).join(", "), DC + 72, y, 8);
  y -= 12;

  txt(page, bold, "Phone:", PC, y, 8);
  txt(page, font, d.plaintiffPhone ?? "", PC + 36, y, 8);
  txt(page, bold, "Phone:", DC, y, 8);
  txt(page, font, d.defendantPhone ?? "", DC + 36, y, 8);
  y -= 12;

  if (d.defendantIsBusinessOrEntity) {
    txt(page, font, "Defendant is a corporation, LLC, or other business entity.", DC + 2, y, 7.5, GRAY);
    y -= 11;
    if ((d as any).defendantAgentName) {
      txt(page, bold, "Agent:", DC, y, 8);
      txt(page, font, (d as any).defendantAgentName, DC + 34, y, 8);
      y -= 11;
      if ((d as any).defendantAgentStreet) {
        txt(page, bold, "Agent addr:", DC, y, 8);
        txt(page, font, `${(d as any).defendantAgentStreet}, ${(d as any).defendantAgentCity ?? ""} ${(d as any).defendantAgentState ?? ""} ${(d as any).defendantAgentZip ?? ""}`.trim(), DC + 58, y, 7.5);
        y -= 11;
      }
    }
  }

  y -= 4;
  drawLine(page, ML, y, MR, y, 0.5);
  y -= 14;

  // ── Claim amount ─────────────────────────────────────────────────────────────
  drawRect(page, ML, y - 1, MR - ML, 14, LIGHT);
  txt(page, bold, "AMOUNT CLAIMED", ML + 4, y + 2, 9);
  txt(page, bold, "Claim Limit: $5,000 (A.R.S. § 22-503)", MR - 220, y + 2, 7.5, GRAY);
  y -= 18;

  const claimAmt = Number(d.claimAmount ?? 0);
  txt(page, bold, "Principal amount: $", ML, y, 9);
  txt(page, font, fmtAmount(claimAmt), ML + 110, y, 9);
  y -= 13;
  txt(page, bold, "Total claimed: $", ML, y, 9);
  txt(page, font, fmtAmount(claimAmt), ML + 94, y, 9);
  txt(page, font, "(exclusive of interest and court costs)", ML + 94 + font.widthOfTextAtSize(fmtAmount(claimAmt), 9) + 8, y, 7.5, GRAY);
  y -= 16;

  drawLine(page, ML, y, MR, y, 0.5);
  y -= 14;

  // ── Statement of claim ───────────────────────────────────────────────────────
  drawRect(page, ML, y - 1, MR - ML, 14, LIGHT);
  txt(page, bold, "STATEMENT OF CLAIM", ML + 4, y + 2, 9);
  y -= 18;

  // Incident date
  if (d.incidentDate) {
    txt(page, bold, "Date claim arose:", ML, y, 8.5);
    txt(page, font, fmtDate(d.incidentDate), ML + 100, y, 8.5);
    y -= 13;
  }

  // Claim type
  if ((d as any).claimType) {
    txt(page, bold, "Nature of claim:", ML, y, 8.5);
    txt(page, font, (d as any).claimType, ML + 96, y, 8.5);
    y -= 13;
  }

  txt(page, bold, "Basis for claim:", ML, y, 8.5);
  y -= 12;
  const desc = d.claimDescription ?? "";
  if (desc) {
    y = wrapText(page, font, desc, ML, y, MR - ML, 8.5, 3.5);
  } else {
    for (let i = 0; i < 4; i++) { drawLine(page, ML, y, MR, y, 0.3, GRAY); y -= 14; }
  }
  y -= 4;

  if ((d as any).howAmountCalculated) {
    txt(page, bold, "How amount was calculated:", ML, y, 8.5);
    y -= 12;
    y = wrapText(page, font, (d as any).howAmountCalculated, ML, y, MR - ML, 8, 3);
    y -= 4;
  }

  // Prior demand
  if ((d as any).demandLetterSentDate) {
    txt(page, font, `Demand letter sent: ${fmtDate((d as any).demandLetterSentDate)}. Defendant has not paid.`, ML, y, 8);
    y -= 13;
  }

  drawLine(page, ML, y, MR, y, 0.5);
  y -= 14;

  // ── Venue / court selection ──────────────────────────────────────────────────
  drawRect(page, ML, y - 1, MR - ML, 14, LIGHT);
  txt(page, bold, "VENUE", ML + 4, y + 2, 9);
  y -= 16;
  txt(page, font, "The defendant resides in, or the events giving rise to this claim occurred in, this justice court precinct.", ML, y, 8);
  y -= 13;
  if (county) {
    txt(page, bold, "County:", ML, y, 8.5);
    txt(page, font, `${county} County, Arizona`, ML + 42, y, 8.5);
    y -= 13;
  }
  y -= 4;

  drawLine(page, ML, y, MR, y, 0.5);
  y -= 14;

  // ── Military service ─────────────────────────────────────────────────────────
  drawRect(page, ML, y - 1, MR - ML, 14, LIGHT);
  txt(page, bold, "SERVICEMEMBERS CIVIL RELIEF ACT", ML + 4, y + 2, 8.5);
  y -= 16;
  page.drawRectangle({ x: ML, y: y - 1, width: 8, height: 8, borderColor: BLACK, borderWidth: 0.7 });
  txt(page, font, "X", ML + 1.5, y, 8);
  txt(page, font, "I do not know whether the defendant is an active-duty member of the U.S. armed forces.", ML + 12, y, 7.5);
  y -= 16;

  drawLine(page, ML, y, MR, y, 0.5);
  y -= 14;

  // ── Declaration / signature ──────────────────────────────────────────────────
  const declText =
    "I declare under penalty of perjury under the laws of the State of Arizona that the information " +
    "in this complaint is true and correct to the best of my knowledge and belief.";
  y = wrapText(page, font, declText, ML, y, MR - ML, 8, 3);
  y -= 20;

  const sigLineY = y;
  drawLine(page, ML, y, ML + 220, y, 0.5);
  txt(page, font, `Date: ${new Date().toLocaleDateString("en-US", { month: "2-digit", day: "2-digit", year: "numeric" })}`, ML + 235, y + 2, 9);
  y -= 4;
  txt(page, font, "Plaintiff signature", ML, y, 7.5, GRAY);
  y -= 12;
  txt(page, bold, "Print name:", ML, y, 9);
  txt(page, font, d.plaintiffName ?? "", ML + 62, y, 9);
  y -= 20;

  // ── Footer ───────────────────────────────────────────────────────────────────
  drawLine(page, ML, y, MR, y, 0.4, TEAL);
  y -= 10;
  const footer = `AZ Small Claims Complaint — Claim limit $5,000 (A.R.S. § 22-503) — No appeal (A.R.S. § 22-519) — Filing fee: $30 flat (A.R.S. § 22-281)`;
  const fw = font.widthOfTextAtSize(footer, 6.3);
  txt(page, font, footer, (PW - fw) / 2, y, 6.3, GRAY);

  if (opts?.signatureBytes) {
    try {
      const sigImg = await doc.embedPng(opts.signatureBytes).catch(() => null)
        ?? await doc.embedJpg(opts.signatureBytes).catch(() => null);
      if (sigImg) page.drawImage(sigImg, { x: ML, y: sigLineY, width: 200, height: 34 });
    } catch { /* ignore invalid image data */ }
  }

  return Buffer.from(await doc.save());
}

const azComplaintDefinition: FormDefinition = {
  state: "AZ",
  formId: "AZ-COMPLAINT",
  renderingTechnique: "png-overlay",
  async generate(d: CaseData, body: FormBody, opts?: GenerateOptions): Promise<Buffer> {
    return buildAZComplaint(d, body, opts);
  },
};

FormRegistry.register(azComplaintDefinition);
export { azComplaintDefinition };
