/**
 * WA MISC 05.0100 — Notice of Small Claim (District Court of Washington)
 *
 * Programmatically generated with pdf-lib (no template PDF required) — the
 * official courts.wa.gov PDF has no fillable AcroForm fields (`pdftk dump_data_fields`
 * returns none), so this follows the same png-overlay-style precedent as
 * VA DC-402 / NC AOC-CVM-200: a fresh, professionally laid-out PDF rather than
 * an overlay on the scanned government page.
 *
 * Legal basis:
 *   RCW 12.40.020, .050, .060, .070 — Small Claims Department, District Court of Washington
 *   Claim limit: $10,000 (RCW 12.40.010); assignees/collection agencies may not file
 *   Form MISC 05.0100 (01/2025)
 */

import { PDFDocument, PDFPage, StandardFonts, rgb, PDFFont } from "pdf-lib";
import type { FormDefinition, FormBody, GenerateOptions } from "../registry";
import { FormRegistry } from "../registry";
import type { CaseData } from "../types";

const PW = 612;
const PH = 792;
const BLACK = rgb(0, 0, 0);
const GRAY = rgb(0.5, 0.5, 0.5);
const LIGHT = rgb(0.93, 0.93, 0.93);

const ML = 54;
const MR = PW - 54;

function drawLine(page: PDFPage, x1: number, y1: number, x2: number, y2: number, thickness = 0.5, color = BLACK) {
  page.drawLine({ start: { x: x1, y: y1 }, end: { x: x2, y: y2 }, thickness, color });
}

function drawRect(page: PDFPage, x: number, y: number, w: number, h: number, fill = LIGHT) {
  page.drawRectangle({ x, y, width: w, height: h, color: fill, borderColor: BLACK, borderWidth: 0.5 });
}

function txt(page: PDFPage, font: PDFFont, text: string | null | undefined, x: number, y: number, size = 9, color = BLACK) {
  if (!text) return;
  page.drawText(String(text), { x, y, size, font, color });
}

function wrapText(page: PDFPage, font: PDFFont, text: string, x: number, y: number, maxWidth: number, size = 9, lineGap = 4): number {
  const words = text.replace(/\r/g, "").split(/\s+/).filter(Boolean);
  let line = "";
  let curY = y;
  for (const word of words) {
    const candidate = line ? line + " " + word : word;
    if (font.widthOfTextAtSize(candidate, size) > maxWidth && line) {
      txt(page, font, line, x, curY, size);
      curY -= size + lineGap;
      line = word;
    } else {
      line = candidate;
    }
  }
  if (line) { txt(page, font, line, x, curY, size); curY -= size + lineGap; }
  return curY;
}

function checkbox(page: PDFPage, font: PDFFont, checked: boolean, x: number, y: number, size = 9) {
  page.drawRectangle({ x, y: y - 1, width: size, height: size, borderColor: BLACK, borderWidth: 0.7 });
  if (checked) txt(page, font, "X", x + 1.5, y, size - 1);
}

function fmtAmount(amount: number | null | undefined): string {
  if (!amount) return "";
  return amount.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function fmtDate(iso?: string | null): string {
  if (!iso) return "";
  const [y, m, d] = iso.split("-");
  if (!y || !m || !d) return iso;
  return `${m}/${d}/${y}`;
}

function countyDisplay(countyId?: string | null): string {
  if (!countyId) return "";
  return countyId
    .replace(/^wa-/, "")
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

function claimReasonLabel(ct?: string | null): string {
  const MAP: Record<string, string> = {
    goods: "Merchandise",
    services: "Faulty Workmanship",
    loan: "Loan",
    account_stated: "Other",
    contract: "Other",
    rent: "Rent",
    property_damage: "Property Damage",
    personal_injury: "Auto Damage - Accident",
    security_deposit: "Return of Deposit",
    other: "Other",
  };
  return ct ? (MAP[ct] ?? "Other") : "Other";
}

export async function buildWANotice(
  d: CaseData,
  _body: FormBody,
  opts?: GenerateOptions,
): Promise<Buffer> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  const page = doc.addPage([PW, PH]);
  const countyName = countyDisplay((d as any).countyId);

  let y = PH - 36;

  // ── Header ──────────────────────────────────────────────────────────────────
  const hdr1 = `District Court of Washington${countyName ? `, County of ${countyName}` : ""}`;
  const hdr2 = "NOTICE OF SMALL CLAIM";

  const h1w = bold.widthOfTextAtSize(hdr1, 10.5);
  txt(page, bold, hdr1, (PW - h1w) / 2, y, 10.5);
  y -= 15;
  const h2w = bold.widthOfTextAtSize(hdr2, 12);
  txt(page, bold, hdr2, (PW - h2w) / 2, y, 12);
  y -= 10;
  const formNote = "MISC 05.0100 (01/2025) — RCW 12.40.020, .050, .060, .070 | Form generated by Small Claims Genie";
  const fnW = font.widthOfTextAtSize(formNote, 6.8);
  txt(page, font, formNote, (PW - fnW) / 2, y, 6.8, GRAY);
  y -= 12;

  txt(page, bold, "SMALL CLAIM NO.:", MR - 190, y + 24, 8);
  txt(page, font, d.caseNumber ?? "(assigned by court)", MR - 90, y + 24, 8, d.caseNumber ? BLACK : GRAY);

  drawLine(page, ML, y, MR, y, 1.2);
  y -= 14;

  // ── Plaintiff / Defendant columns ────────────────────────────────────────────
  const COL_MID = ML + (MR - ML) / 2;
  drawRect(page, ML, y - 1, COL_MID - ML - 4, 14, LIGHT);
  drawRect(page, COL_MID, y - 1, MR - COL_MID, 14, LIGHT);
  txt(page, bold, "PLAINTIFF (You)", ML + 4, y + 2, 9);
  txt(page, bold, "DEFENDANT", COL_MID + 4, y + 2, 9);
  y -= 16;

  const PC = ML + 4;
  const DC = COL_MID + 4;
  const CW = COL_MID - ML - 12;

  const pName = (d as any).plaintiffDbaName
    ? `${d.plaintiffName ?? ""} d/b/a ${(d as any).plaintiffDbaName}`
    : (d.plaintiffName ?? "");

  txt(page, bold, "Name:", PC, y, 8);
  txt(page, font, pName, PC + 34, y, 8);
  txt(page, bold, "Name:", DC, y, 8);
  txt(page, font, d.defendantName ?? "", DC + 34, y, 8);
  y -= 12;

  txt(page, bold, "Addr:", PC, y, 8);
  wrapText(page, font, d.plaintiffAddress ?? "", PC + 34, y, CW - 34, 8, 3);
  txt(page, bold, "Addr:", DC, y, 8);
  wrapText(page, font, d.defendantAddress ?? "", DC + 34, y, CW - 34, 8, 3);
  y -= 12;

  txt(page, bold, "City:", PC, y, 8);
  txt(page, font, [d.plaintiffCity, "WA", d.plaintiffZip].filter(Boolean).join(", "), PC + 34, y, 8);
  txt(page, bold, "City:", DC, y, 8);
  txt(page, font, [d.defendantCity, d.defendantState ?? "WA", d.defendantZip].filter(Boolean).join(", "), DC + 34, y, 8);
  y -= 12;

  txt(page, bold, "Phone:", PC, y, 8);
  txt(page, font, d.plaintiffPhone ?? "", PC + 36, y, 8);
  txt(page, bold, "Phone:", DC, y, 8);
  txt(page, font, d.defendantPhone ?? "", DC + 36, y, 8);
  y -= 12;

  if (d.defendantIsBusinessOrEntity) {
    txt(page, bold, "Entity:", DC, y, 8);
    txt(page, font, "Defendant is a LLC, corporation, or other business entity.", DC + 38, y, 7.5);
    y -= 11;
    if ((d as any).defendantAgentName) {
      txt(page, bold, "Agent:", DC, y, 8);
      txt(page, font, (d as any).defendantAgentName, DC + 34, y, 8);
      y -= 11;
    }
  }

  y -= 4;
  drawLine(page, ML, y, MR, y, 0.5);
  y -= 14;

  // ── Claim amount ────────────────────────────────────────────────────────────
  drawRect(page, ML, y - 1, MR - ML, 14, LIGHT);
  txt(page, bold, "THE PLAINTIFF CLAIMS YOU OWE", ML + 4, y + 2, 9);
  y -= 18;

  const claimAmt = Number(d.claimAmount ?? 0);
  txt(page, bold, "Principal: $", ML, y, 9);
  txt(page, font, fmtAmount(claimAmt), ML + 66, y, 9);
  txt(page, bold, "Claim Limit: $10,000 (RCW 12.40.010)", MR - 195, y, 7.5, GRAY);
  y -= 13;
  txt(page, bold, "Total: $", ML, y, 9);
  txt(page, font, fmtAmount(claimAmt), ML + 46, y, 9);
  y -= 16;

  drawLine(page, ML, y, MR, y, 0.5);
  y -= 14;

  // ── Statement of claim ───────────────────────────────────────────────────────
  drawRect(page, ML, y - 1, MR - ML, 14, LIGHT);
  txt(page, bold, "STATEMENT OF CLAIM", ML + 4, y + 2, 9);
  y -= 18;

  txt(page, font, `I, ${d.plaintiffName ?? ""}, declare that the defendant named above owes me the`, ML, y, 8.5);
  y -= 11;
  txt(page, font, `sum of $${fmtAmount(claimAmt)}, which was due and owing on ${fmtDate(d.incidentDate) || "the date below"}.`, ML, y, 8.5);
  y -= 14;

  const reason = claimReasonLabel((d as any).claimType);
  const reasons = ["Faulty Workmanship", "Merchandise", "Auto Damage", "Wages", "Loan", "Return of Deposit", "Rent", "Property Damage", "Other"];
  txt(page, bold, "The amount owed is for:", ML, y, 8.5);
  y -= 12;
  let cx = ML;
  for (const r of reasons) {
    const isMatch = reason === r || (reason === "Auto Damage - Accident" && r === "Auto Damage");
    checkbox(page, font, isMatch, cx, y, 8);
    txt(page, font, r, cx + 11, y, 7.5);
    cx += font.widthOfTextAtSize(r, 7.5) + 24;
    if (cx > MR - 70) { cx = ML; y -= 12; }
  }
  y -= 14;

  txt(page, bold, "Explain reason for claim:", ML, y, 8.5);
  y -= 12;
  const desc = d.claimDescription ?? "";
  if (desc) {
    y = wrapText(page, font, desc, ML, y, MR - ML, 8.5, 3.5);
  } else {
    for (let i = 0; i < 3; i++) { drawLine(page, ML, y, MR, y, 0.3, GRAY); y -= 13; }
  }
  y -= 6;

  if ((d as any).howAmountCalculated) {
    txt(page, bold, "How amount was calculated:", ML, y, 8.5);
    y -= 11;
    y = wrapText(page, font, (d as any).howAmountCalculated, ML, y, MR - ML, 8, 3);
    y -= 6;
  }

  drawLine(page, ML, y, MR, y, 0.5);
  y -= 14;

  // ── Military service ─────────────────────────────────────────────────────────
  drawRect(page, ML, y - 1, MR - ML, 14, LIGHT);
  txt(page, bold, "MILITARY SERVICE (Servicemembers Civil Relief Act)", ML + 4, y + 2, 8.5);
  y -= 16;
  checkbox(page, font, true, ML, y, 8);
  txt(page, font, "I do not know if any defendants are covered by the Servicemember Civil Relief Act.", ML + 12, y, 7.5);
  y -= 16;

  drawLine(page, ML, y, MR, y, 0.5);
  y -= 14;

  // ── Certification / signature ────────────────────────────────────────────────
  const certText =
    "I certify under penalty of perjury under the laws of the State of Washington that all the information " +
    "provided in this notice and any attachments is true and correct.";
  y = wrapText(page, font, certText, ML, y, MR - ML, 8, 3);
  y -= 16;

  const sigLineY = y;
  drawLine(page, ML, y, ML + 200, y, 0.5);
  txt(page, font, `Date: ${new Date().toLocaleDateString("en-US", { month: "2-digit", day: "2-digit", year: "numeric" })}`, ML + 215, y + 2, 9);
  y -= 4;
  txt(page, font, "Sign here", ML, y, 7.5, GRAY);
  y -= 12;
  txt(page, bold, "Print name:", ML, y, 9);
  txt(page, font, d.plaintiffName ?? "", ML + 62, y, 9);
  y -= 20;

  // ── Footer ──────────────────────────────────────────────────────────────────
  drawLine(page, ML, y, MR, y, 0.4);
  y -= 10;
  const footer = "MISC 05.0100 — WA Notice of Small Claim — Claim limit: $10,000 (RCW 12.40.010) — Assignees and collection agencies may not file";
  const fw = font.widthOfTextAtSize(footer, 6.5);
  txt(page, font, footer, (PW - fw) / 2, y, 6.5, GRAY);

  if (opts?.signatureBytes) {
    try {
      const sigImg = await doc.embedPng(opts.signatureBytes).catch(() => null)
        ?? await doc.embedJpg(opts.signatureBytes).catch(() => null);
      if (sigImg) page.drawImage(sigImg, { x: ML, y: sigLineY, width: 180, height: 32 });
    } catch { /* ignore invalid image data */ }
  }

  return Buffer.from(await doc.save());
}

const waNoticeDefinition: FormDefinition = {
  state: "WA",
  formId: "WA-MISC05-0100",
  renderingTechnique: "png-overlay",
  async generate(d: CaseData, body: FormBody, opts?: GenerateOptions): Promise<Buffer> {
    return buildWANotice(d, body, opts);
  },
};

FormRegistry.register(waNoticeDefinition);
export { waNoticeDefinition };
