/**
 * WA MISC 05.0200 — Certificate of Service (District Court of Washington)
 *
 * Programmatically generated with pdf-lib (no template PDF required) — same
 * approach as WA MISC 05.0100 (no fillable AcroForm fields on the official PDF).
 *
 * Legal basis: RCW 12.40.040 — proof that the Notice of Small Claim was served
 * on the defendant. Filed with the court after service is completed.
 * Form MISC 05.0200 (01/2025)
 */

import { PDFDocument, PDFPage, StandardFonts, rgb, PDFFont } from "pdf-lib";
import type { FormDefinition, FormBody, GenerateOptions } from "../registry";
import { FormRegistry } from "../registry";
import type { CaseData } from "../types";

const PW = 612;
const PH = 792;
const BLACK = rgb(0, 0, 0);
const GRAY = rgb(0.5, 0.5, 0.5);
const LIGHT = rgb(0.93, 0.93, 0.93);

const ML = 54;
const MR = PW - 54;

function drawLine(page: PDFPage, x1: number, y1: number, x2: number, y2: number, thickness = 0.5, color = BLACK) {
  page.drawLine({ start: { x: x1, y: y1 }, end: { x: x2, y: y2 }, thickness, color });
}

function drawRect(page: PDFPage, x: number, y: number, w: number, h: number, fill = LIGHT) {
  page.drawRectangle({ x, y, width: w, height: h, color: fill, borderColor: BLACK, borderWidth: 0.5 });
}

function txt(page: PDFPage, font: PDFFont, text: string | null | undefined, x: number, y: number, size = 9, color = BLACK) {
  if (!text) return;
  page.drawText(String(text), { x, y, size, font, color });
}

function checkbox(page: PDFPage, font: PDFFont, checked: boolean, x: number, y: number, size = 9) {
  page.drawRectangle({ x, y: y - 1, width: size, height: size, borderColor: BLACK, borderWidth: 0.7 });
  if (checked) txt(page, font, "X", x + 1.5, y, size - 1);
}

function countyDisplay(countyId?: string | null): string {
  if (!countyId) return "";
  return countyId
    .replace(/^wa-/, "")
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

export async function buildWAService(
  d: CaseData,
  _body: FormBody,
  opts?: GenerateOptions,
): Promise<Buffer> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  const page = doc.addPage([PW, PH]);
  const countyName = countyDisplay((d as any).countyId);

  let y = PH - 36;

  const hdr1 = `District Court of Washington${countyName ? `, County of ${countyName}` : ""}`;
  const h1w = bold.widthOfTextAtSize(hdr1, 10.5);
  txt(page, bold, hdr1, (PW - h1w) / 2, y, 10.5);
  y -= 15;
  const hdr2 = "CERTIFICATE OF SERVICE";
  const h2w = bold.widthOfTextAtSize(hdr2, 12);
  txt(page, bold, hdr2, (PW - h2w) / 2, y, 12);
  y -= 10;
  const formNote = "MISC 05.0200 (01/2025) — RCW 12.40.040 | Form generated by Small Claims Genie";
  const fnW = font.widthOfTextAtSize(formNote, 6.8);
  txt(page, font, formNote, (PW - fnW) / 2, y, 6.8, GRAY);
  y -= 14;

  txt(page, bold, "No.:", ML, y, 9);
  txt(page, font, d.caseNumber ?? "(assigned by court)", ML + 30, y, 9, d.caseNumber ? BLACK : GRAY);
  y -= 12;
  txt(page, bold, "Plaintiff:", ML, y, 9);
  txt(page, font, d.plaintiffName ?? "", ML + 54, y, 9);
  y -= 12;
  txt(page, bold, "vs. Defendant:", ML, y, 9);
  txt(page, font, d.defendantName ?? "", ML + 80, y, 9);
  y -= 16;

  drawLine(page, ML, y, MR, y, 1);
  y -= 16;

  txt(page, font, "I, (Name)", ML, y, 9);
  drawLine(page, ML + 58, y - 2, ML + 260, y - 2, 0.5);
  txt(page, font, "declare that I am not the plaintiff,", ML + 265, y, 8.5);
  y -= 12;
  txt(page, font, "defendant, or a witness, and I served the Notice of Small Claim on:", ML, y, 8.5);
  y -= 16;

  drawRect(page, ML, y - 1, MR - ML, 14, LIGHT);
  txt(page, bold, "Name of Defendant", ML + 4, y + 2, 8);
  txt(page, bold, "Address Where Served", ML + 190, y + 2, 8);
  txt(page, bold, "Date of Service", ML + 400, y + 2, 8);
  y -= 18;
  txt(page, font, d.defendantName ?? "", ML + 4, y, 8.5);
  txt(page, font, d.defendantAddress ?? "", ML + 190, y, 8.5);
  y -= 16;

  if (d.defendantIsBusinessOrEntity) {
    checkbox(page, font, true, ML, y, 9);
    txt(page, font, "Defendant is a LLC, corporation, or other business entity.", ML + 12, y, 8.5);
    y -= 12;
    if ((d as any).defendantAgentName) {
      txt(page, bold, "Title and Name of Person Served:", ML, y, 8.5);
      txt(page, font, (d as any).defendantAgentName, ML + 168, y, 8.5);
      y -= 12;
    }
  }
  y -= 6;
  drawLine(page, ML, y, MR, y, 0.5);
  y -= 16;

  txt(page, bold, "By:", ML, y, 9);
  y -= 4;
  checkbox(page, font, false, ML, y, 9);
  txt(page, bold, "PERSONAL SERVICE", ML + 12, y, 9);
  y -= 12;
  txt(page, font, "I served the above by delivering a true copy to the defendant personally in", ML, y, 8, GRAY);
  y -= 10;
  drawLine(page, ML, y, ML + 180, y, 0.4, GRAY);
  txt(page, font, "County, State of Washington at the above address.", ML + 185, y + 2, 8, GRAY);
  y -= 16;

  checkbox(page, font, false, ML, y, 9);
  txt(page, bold, "SUBSTITUTE SERVICE", ML + 12, y, 9);
  y -= 12;
  txt(page, font, "I served the above by delivering a true copy to the defendant's usual place of abode, and leaving it", ML, y, 8, GRAY);
  y -= 10;
  txt(page, font, "with a person over 12 years of age residing there.", ML, y, 8, GRAY);
  y -= 16;

  checkbox(page, font, false, ML, y, 9);
  txt(page, bold, "SERVICE BY MAIL", ML + 12, y, 9);
  txt(page, font, "(attach postal receipt and return receipt signed by defendant)", ML + 105, y, 7.5, GRAY);
  y -= 20;

  drawLine(page, ML, y, MR, y, 0.5);
  y -= 16;

  const certText =
    "I declare under penalty of perjury that the foregoing is true and correct and that I was, at the time of " +
    "service of the above notice(s), a resident of the State of Washington over the age of 18 years and not a " +
    "party to the above-numbered claim.";
  const words = certText.split(" ");
  let line = "";
  for (const w of words) {
    const candidate = line ? line + " " + w : w;
    if (font.widthOfTextAtSize(candidate, 8) > (MR - ML) && line) {
      txt(page, font, line, ML, y, 8);
      y -= 11;
      line = w;
    } else line = candidate;
  }
  if (line) { txt(page, font, line, ML, y, 8); y -= 11; }
  y -= 12;

  // Note: this certificate is signed by whoever actually performed service
  // (often not the plaintiff — can be a process server, sheriff, or other
  // adult third party). The app only captures the plaintiff/user's
  // e-signature, so it must NOT be auto-embedded here — the "server" signs
  // this line by hand after printing.
  drawLine(page, ML, y, ML + 200, y, 0.5);
  txt(page, font, `Dated: ${new Date().toLocaleDateString("en-US", { month: "2-digit", day: "2-digit", year: "numeric" })}`, ML + 215, y + 2, 9);
  y -= 4;
  txt(page, font, "Signature of Server", ML, y, 7.5, GRAY);
  y -= 20;

  drawLine(page, ML, y, MR, y, 0.4);
  y -= 10;
  const footer = "MISC 05.0200 — WA Certificate of Service — RCW 12.40.040 — File with the court after service is completed";
  const fw = font.widthOfTextAtSize(footer, 6.5);
  txt(page, font, footer, (PW - fw) / 2, y, 6.5, GRAY);

  return Buffer.from(await doc.save());
}

const waServiceDefinition: FormDefinition = {
  state: "WA",
  formId: "WA-MISC05-0200",
  renderingTechnique: "png-overlay",
  async generate(d: CaseData, body: FormBody, opts?: GenerateOptions): Promise<Buffer> {
    return buildWAService(d, body, opts);
  },
};

FormRegistry.register(waServiceDefinition);
export { waServiceDefinition };
